services:
  db:
    container_name: fennec_db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fennec_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db/data:/var/lib/mysql
